// <auto-generated />
namespace CoursWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updtDbLast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updtDbLast));
        
        string IMigrationMetadata.Id
        {
            get { return "202405160623447_updtDbLast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
