// <auto-generated />
namespace CoursWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updlastdbforcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updlastdbforcode));
        
        string IMigrationMetadata.Id
        {
            get { return "202405160627551_updlastdbforcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
